kolla_base_distro: "ubuntu"
kolla_install_type: "source"
openstack_release: "13.0.1"
node_custom_config: "/etc/kolla/config"
docker_registry: "${public_ip}:4000"
docker_registry_insecure: "yes"
docker_namespace: "kolla"
#network_interface:  "enP4p4s0f0"
#neutron_external_interface: "enp1s0f1,enP4p4s0f1"
enable_ironic: "yes"
enable_neutron_provider_networks: "yes"
ironic_cleaning_network: baremetal-dataplane
#ironic_dnsmasq_dhcp_range: "192.168.116.101,192.168.116.150,255.255.255.0"
#ironic_dnsmasq_default_gateway: "192.168.116.1"


---
config_strategy: "COPY_ALWAYS"
kolla_base_distro: "ubuntu"
kolla_install_type: "source"
openstack_release: "13.0.1"
node_custom_config: "/etc/kolla/config"
docker_registry: "10.76.97.61:4000"
docker_registry_insecure: "True"
enable_nova_serialconsole_proxy: "yes"
enable_neutron_provider_networks: "yes"
nova_compute_virt_type: "kvm"
# Multinode Specific
# kolla_internal_vip_address: "192.168.97.100"
# kolla_external_vip_address: "10.76.97.200"
# kolla_external_fqdn: "openstack.scc-lab.amperecomputing.com"
# enable_haproxy: "yes"
# enable_collected: "yes"
# enable_grafana: "yes"
# enable_prometheus: "yes"
enable_ironic: "yes"
enable_ironic_pxe_uefi: "yes"
enable_nova_serialconsole_proxy: "yes"
ironic_dnsmasq_interface: "{{ network_interface }}"
ironic_dnsmasq_dhcp_range: "192.168.97.101,192.168.97.150"
ironic_dnsmasq_default_gateway: "192.168.97.1"
ironic_cleaning_network: "baremetal-dataplane"
ironic_dnsmasq_boot_file: "debian-installer/arm64/grubnetaa64.efi"
#ironic_pxe_extra_volumes:
#  - "/usr/lib/debian-installer/images/10/arm64/text/debian-installer:/tftpboot/debian-installer"
#ironic_conductor_extra_volumes:
#  - "/etc/kolla/config/ironic/pxe_grubaa64_config.template:/ironic/ironic/drivers/modules/pxe_grubaa64_config.template"
